spring.application.name=backend

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME:mr_reporting_db}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Hibernate / JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# A secure, 256-bit secret key (must be at least 32 characters long)
jwt.secret=${JWT_SECRET}

# Token expiration time in milliseconds (86400000 ms = 24 hours)
jwt.expiration=86400000
